-- AlterTable
ALTER TABLE "otps" ALTER COLUMN "userId" SET DATA TYPE TEXT,
ALTER COLUMN "admin_id" SET DATA TYPE TEXT;

-- AddForeignKey
ALTER TABLE "otps" ADD CONSTRAINT "otps_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
